### ISSUE TITLE
cant start the program

### ISSUE THREAD

**Issue by lstxmu** [wpwupingwp/novowrap#1]

**Comment by lstxmu** [comment]
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Comment by wpwupingwp** [comment]
Duplicate of #2
