### ISSUE TITLE
Module missing: six (???)

### ISSUE THREAD

**Issue by NowickiLab** [wpwupingwp/novowrap#11]
Hi,
Not sure how this is related to novowrap itself, but I ran it few days ago without any problems; and today it shows issues - screenshot below. Reinstall, updating did not solve it.
Thanks for any pointers,
-Marcin
![novowrapSIX](https://user-images.githubusercontent.com/61125735/232807391-c52b0ed3-cdcd-41ed-bf54-751f47186fe4.png)

**Comment by wpwupingwp** [comment]
it seems that your python environment is broken.
Try:
```
# 1. check environment
python3 --version
pip list
# 2. check matplotlib
python3 -c "from matplotlib import _version;print(_version.version)"
# 3. reinstall novowrap
pip3 uninstall novowrap
pip3 install novowrap
```

**Comment by wpwupingwp** [comment]
by the way, I noticed you are using conda, make sure you choose the correct environment

**Comment by NowickiLab** [comment]
Very helpful! I reinstalled from scratch and seems to work now. Cheers!
