### ISSUE TITLE
the progam fail to start

### ISSUE THREAD

**Issue by lstxmu** [wpwupingwp/novowrap#2]
hi ,  i had install the  program follow the instroduction, but the program fail to start.
the error message shows as follow, please help to fix the isssue.
===================================================
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
===================================================

thanks a lot!

**Comment by wpwupingwp** [comment]
Thanks for your note！

This might be due to the conflict of the version of dependent packages.

I will try to fix it in 6 hours.

**Comment by wpwupingwp** [comment]
@lstxmu 

The problem might be fixed now. Please upgrade your novowrap to the newest version, by running
```
pip uninstall novowrap
pip install novowrap -i https://pypi.org/simple
```
and try to run the program again. If you use portable packages, please download the [newest version](https://github.com/wpwupingwp/novowrap/releases/tag/v0.97).

If you find any problem, please let me know.

If ok, please tell me, too. So that I can mark this issue as "solved".

Again, thanks for you help!

Ping Wu

**Comment by lstxmu** [comment]
Dear Ping Wu

Thanks for the quick reply.  I have taken your advice, the failure issue was fixed.  The assembly job was done and the result was perfect.  What a great job! Thnak you.

PS:  I wonder this program can be used to assemble plant/animal  complete mitogenome?

Sincerely,

Site Luo

**Comment by wpwupingwp** [comment]
Dear Luo,
Currently the program only support plastid genomes. If you want to assemble and analyze mitochondria genome, maybe you could try [MitoZ](https://github.com/linzhi2013/MitoZ).

Ping Wu

**Comment by wpwupingwp** [comment]
> Dear Ping Wu
> 
> Thanks for the quick reply. I have taken your advice, the failure issue was fixed. The assembly job was done and the result was perfect. What a great job! Thnak you.
> 
> PS: I wonder this program can be used to assemble plant/animal complete mitogenome?
> 
> Sincerely,
> 
> Site Luo

Dear Luo,
The newest version added support of assembling mitochondria genomes or plastids without normal structure. The usage could be found in the document. 
I have tested with two datasets, maybe you could tried with your own data and please tell me if any problems occurs.

Sincerely
Ping Wu
